### ISSUE TITLE
crash while invoking evhtp_connection_new()

### ISSUE THREAD

**Issue by girishgdesai** [Yellow-Camper/libevhtp#159]
Program terminated with signal 6, Aborted.
#0  0x00007f3d3fefd9e0 in __connect_nocancel () at ../sysdeps/unix/syscall-template.S:81
81      T_PSEUDO (SYSCALL_SYMBOL, SYSCALL_NAME, SYSCALL_NARGS)
Missing separate debuginfos, use: debuginfo-install pw-unicloud-6.0.0.295-20200717.1317-1-0.x86_64
(gdb) bt
#0  0x00007f3d3fefd9e0 in __connect_nocancel () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f3d3c0f40c7 in evutil_socket_connect (fd_ptr=fd_ptr@entry=0x7ffcf7faba54, sa=sa@entry=0x7ffcf7fabad0, socklen=socklen@entry=16)
    at evutil.c:481
#2  0x00007f3d3c0ee731 in bufferevent_socket_connect (bev=0xbf5a000, sa=0x7ffcf7fabad0, socklen=16) at bufferevent_sock.c:392
#3  0x00000000037dc471 in evhtp_connection_new_dns ()
#4  0x00000000037dc20d in evhtp_connection_new ()
#5 *****************
#6 *****************

As I wanted the client to communicate with the server using specific (configurable by user) IP, I created one socket bounded on IP and provided that socket fd to evhtp_connection_new() which passes it to evhtp_connection_new_dns() and then finally to "bufferevent_socket_new()" (instead of -1, which is default argument). It was expected that libevhtp will use this socket to connect with the server. 
But it is crashing sometimes with the above signature.

Am I missing something? Do we have any other better way to fulfill my requirement?

Why doesn't libevthp support client connection establishment using user-defined local IP ?

**Comment by girishgdesai** [comment]
This crash was seen due to some internal error handling case in our code, not related to evhtp
